# Author: XTofTech
# Mapper for MCP tool names to descriptive sentences

TOOL_NAME_MAP = {
    "get_site_info": "Retrieving inventory and location details for a specific site.",
    "net_get_devices_management_ip": "Resolving the management IP address for a network device.",
    "net_find_network_interfaces": "Listing all physical and logical interfaces on a device.",
    "net_get_network_device_arp_table": "Inspecting the IP-to-MAC address resolution (ARP) table.",
    "net_get_switch_mac_address_table": "Querying the L2 switching table for connected MAC addresses.",
    "net_get_l2_forwarding_information": "Analyzing VLAN trunks and Spanning Tree Protocol (STP) status.",
    "net_get_nat_table": "Retrieving active Network Address Translation (NAT) mappings.",
    "net_get_routing_table": "Accessing the IP routing table to verify network paths.",
    "net_capture_network_traffic": "Starting a live packet capture on a device interface.",
    "net_get_device_logs": "Extracting system event logs for diagnostic analysis.",
    "net_run_commands_on_device": "Executing administrative commands directly on a device.",
    "servicenow_get_incidents_by_priority": "Filtering ServiceNow incidents by their priority level.",
    "servicenow_get_incidents_by_incident_id": "Looking up a specific ServiceNow incident by its number.",
    "servicenow_get_incidents_by_user": "Retrieving tickets assigned to a specific ServiceNow user.",
    "servicenow_get_unassigned_incidents_for_group": "Scanning for unassigned tickets in a ServiceNow group.",
    "servicenow_create_incident": "Logging a new support incident in the ServiceNow system.",
    "servicenow_create_change_request": "Raising a formal change management request in ServiceNow.",
    "jira_get_ticket": "Fetching basic status and summary for a Jira project ticket.",
    "jira_get_ticket_details": "Accessing full details, comments, and history of a Jira ticket.",
    "jira_update_ticket": "Updating fields such as priority or labels on a Jira ticket.",
    "jira_add_comment": "Appending a new comment or update to a Jira ticket.",
    "jira_transition_ticket": "Moving a Jira ticket to its next workflow status.",
    "jira_list_transitions": "Identifying available workflow actions for a Jira ticket.",
    "jira_get_recent_tickets": "Monitoring the most recently created tickets in Jira.",
    "jira_get_tickets_by_assignee": "Listing all Jira tasks currently assigned to a user.",
    "jira_search_tickets": "Executing a custom JQL search to find specific Jira tickets.",
    "cloud_ssh_tool": "Managing cloud virtual machines via secure remote access.",
    "linux_server_ssh_tool": "Accessing a remote Linux server to perform administrative tasks.",
    "execute_shell_command": "Running host system utilities and diagnostic scripts.",
    "execute_generated_code": "Executing sandboxed Python code for complex data processing.",
    "net_execute_with_tool_modification": "Applying custom post-processing to another tool's output.",
    "visualize_drawio_diagram": "Converting Draw.io XML into a visual diagram render.",
    "analyze_drawio_diagram": "Performing a logical audit of a network diagram's XML.",
    "archive_current_conversation": "Saving the current session into the long-term knowledge base.",
    "archive_local_document": "Ingesting documentation files for future retrieval and RAG.",
    "query_agent_archives": "Searching archived data to recall past solutions and facts.",
    "get_skill_all_related_tools": "Discovering available tools associated with a specific agent skill.",
    "rest_api_call": "Communicating with external services via generic REST requests.",
    "rest_api_inspect_env": "Checking API credential prefixes and environment health.",
    "search_internet": "Searching the internet for the most recent information and documentation.",
    "user_clarification_and_action_tool": "Requesting clarification or manual action from the user.",
    "nms_browser": "Navigating a GUI-based Network System or researching documentation.",
    "write_todos": "Updating the internal task list and project plan.",
    "ls": "Listing files in the current workspace directory.",
    "read_file": "Reading the content of a local file.",
    "write_file": "Creating or overwriting a file with new content.",
    "edit_file": "Applying targeted edits to an existing file.",
    "glob": "Searching for files matching a specific pattern.",
    "grep": "Searching for text patterns within files.",
    "execute": "Executing a host system command or diagnostic script.",
}
